### PR TITLE
Literally just changed the headings this time

### PR DESCRIPTION
**Pull request by tryoxiss**
There I hope this works, headings are now semantic, and that is the only change.

### CODE REVIEW

**Comment by jacobxperez** [comment]
@tryoxiss LOL the commit title. You can also add sectioning tags to wrap each h2 heading with its content if you want. Sorry the last pull-request change things that were not discussed in issue  #18

**Comment by tryoxiss** [comment]
> @tryoxiss LOL the commit title. You can also add sectioning tags to wrap each h2 heading with its content if you want. Sorry the last pull-request change things that were not discussed in issue #18

I am glad you find it amusing! Its ok, I just figured they were minor and directly related to the goal of semantics. Section tags are not really needed as the entire page is functionally 1 section, but I may do that in the future. (I just find it a main)

**Comment by jacobxperez** [comment]
@tryoxiss Alright thanks I will close this issue but please feel free to open any [issue](https://github.com/jacobxperez/atkinson-hyperlegible-pro/issues) or [discussion](https://github.com/jacobxperez/atkinson-hyperlegible-pro/discussions), any contribution or feedback is always welcomed.

**Comment by tryoxiss** [comment]
> @tryoxiss Alright thanks I will close this issue but please feel free to open any [issue](https://github.com/jacobxperez/atkinson-hyperlegible-pro/issues) or [discussion](https://github.com/jacobxperez/atkinson-hyperlegible-pro/discussions), any contribution or feedback is always welcomed.

Thanks, I will!

**Pull request merged**
