### PR TITLE
✨ Use semantic elements instead of data- attributes.

### PR DESCRIPTION
**Pull request by tryoxiss**
- Changed all headings to heading elements. This caused some variables to change aswell, but the layout is identical.
- Changed contibute link to go to CONTRIBUTING.md instead of the repos home.

### CODE REVIEW

**Comment by jacobxperez** [comment]
@tryoxiss Wait this makes to many changes. try not to make changes to the **[Core](https://github.com/jacobxperez/atkinson-hyperlegible-pro/tree/website/src/css/core)** folder because that is part of the [Rams](https://github.com/jacobxperez/rams) framework that's another project I been working on. [Custom](https://github.com/jacobxperez/atkinson-hyperlegible-pro/tree/website/src/css/custom) folder as well as the [main.css](https://github.com/jacobxperez/atkinson-hyperlegible-pro/blob/website/src/css/main.css) and [var.css](https://github.com/jacobxperez/atkinson-hyperlegible-pro/blob/website/src/css/var.css) are okay to edit however you don't have to edit this files to add semantics just the html files.

If we compare the current build this section is supposed to be for display only and not necessarily changed to an HTML heading
Screenshot 2023-10-24 at 17-22-05 Atkinson Hyperlegible Pro - 88 Extra Glyphs Including an Alternative Flipped Zero Improved Kerning and Ligatures

Your build makes this section smaller 
Screenshot 2023-10-24 at 17-21-56 Atkinson Hyperlegible Pro - 88 Extra Glyphs Including an Alternative Flipped Zero Improved Kerning and Ligatures

This section is also for display and having a p tag with the data attributes  is fine 
Screenshot 2023-10-24 at 17-25-18 Atkinson Hyperlegible Pro - 88 Extra Glyphs Including an Alternative Flipped Zero Improved Kerning and Ligatures

Current built has bigger characters for dis[play 
Screenshot 2023-10-24 at 17-39-41 Atkinson Hyperlegible Pro - 88 Extra Glyphs Including an Alternative Flipped Zero Improved Kerning and Ligatures


Quick tips
* Do not edit core files 
* Custom folder, main.css var.css are fine to edit but you don't have to for this implementation.
* Only change the section headings to their corresponding h-tag 

Pleas let me know if I am clear or if you have any questions I'll be glad to answer

**Comment by jacobxperez** [comment]
@tryoxiss I forgot to mention any new CSS file should go in the [Custom](https://github.com/jacobxperez/atkinson-hyperlegible-pro/tree/website/src/css/custom) folder and also the contribute link should take you directly to the GitHub repo.

**Comment by jacobxperez** [comment]
We can also use the sectioning tag to wrap each section

**Comment by tryoxiss** [comment]
> If we compare the current build this section is supposed to be for display only and not necessarily changed to an HTML heading Screenshot 2023-10-24 at 17-22-05 Atkinson Hyperlegible Pro - 88 Extra Glyphs Including an Alternative Flipped Zero Improved Kerning and Ligatures

Oh I didn't realise that, I did compare to the original I must have missed that.

> This section is also for display and having a p tag with the data attributes is fine Screenshot 2023-10-24 at 17-25-18 Atkinson Hyperlegible Pro - 88 Extra Glyphs Including an Alternative Flipped Zero Improved Kerning and Ligatures

This section is still using data- attributes!

> Current built has bigger characters for display Screenshot 2023-10-24 at 17-39-41 Atkinson Hyperlegible Pro - 88 Extra Glyphs Including an Alternative Flipped Zero Improved Kerning and Ligatures


> Quick tips
> 
>     * Do not edit core files

I assumed they were just basic styles and fine to edit but ok.

>     * Custom folder, main.css var.css are fine to edit but you don't have to for this implementation.

Its still better and more legible for devs to use semantic elements as opposed to adding semantics after but sure ill fix that.

>     * Only change the section headings to their corresponding h-tag

I did, it changed thier size (since your h2's are h2 size, but h3's are h4 size, etc)

> Pleas let me know if I am clear or if you have any questions I'll be glad to answer

EDIT: Oops, I didn't mean to close it! I just wanted to revert my forks changes to do the stuff you said.

**Pull request closed without merging**
